import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RootStyleRegistry from "./emotion";
import { Notifications } from "@mantine/notifications";
import { RouterTransition } from "@/components/RouterTransition";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootStyleRegistry>
          <Notifications />
          <RouterTransition />
          {children}
        </RootStyleRegistry>
      </body>
    </html>
  );
}
